version: "3"
services:
  web:
    image: aliadnansohail/docker-practice
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - /usr/src/app
    networks:
      - devstack_default

networks:
  devstack_default:
    external: true
